services:
  - type: web
    name: social-app
    runtime: node
    region: frankfurt
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000